# Generated by Django 2.2.9 on 2020-01-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='عنوان پست'),
            preserve_default=False,
        ),
    ]
