# Generated by Django 2.2.9 on 2020-02-03 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='مولف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='down_voted_users',
            field=models.ManyToManyField(related_name='down_voted_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که رای منفی ثبت کردند'),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_voted_users',
            field=models.ManyToManyField(related_name='up_voted_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که رای مثبت ثبت کردند'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='مولف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='down_voted_users',
            field=models.ManyToManyField(related_name='down_voted_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که رای منفی ثبت کردند'),
        ),
        migrations.AddField(
            model_name='post',
            name='up_voted_users',
            field=models.ManyToManyField(related_name='up_voted_posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که رای مثبت ثبت کردند'),
        ),
    ]
