# Generated by Django 2.2.9 on 2020-01-31 18:39

import _helpers.db.utils.rename_on_upload
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('message', models.CharField(max_length=64, verbose_name='پیام')),
                ('url', models.URLField(verbose_name='لینک هشدار')),
            ],
            options={
                'get_latest_by': '-created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=_helpers.db.utils.rename_on_upload.RenameOnUpload('/images/profiles/'), verbose_name='عکس پروفایل')),
                ('location', models.CharField(blank=True, max_length=32, verbose_name='مکان')),
                ('reset_password_uuid', models.UUIDField(verbose_name='کد مربوط به لینک فراموشی رمز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'get_latest_by': '-created',
                'abstract': False,
            },
        ),
    ]
