# Generated by Django 2.2.9 on 2020-02-01 00:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200201_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reset_password_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='کد مربوط به لینک فراموشی رمز'),
        ),
    ]
